# Generated by Django 5.2.12 on 2026-03-25 20:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField()),
                ('company', models.CharField()),
                ('applied_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('job_description', models.TextField()),
            ],
        ),
    ]
