# Generated by Django 5.2.12 on 2026-03-25 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextstep', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='company_link',
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name='application',
            name='role_link',
            field=models.CharField(blank=True),
        ),
    ]
