# Generated by Django 5.2.12 on 2026-03-25 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextstep', '0002_application_company_link_application_role_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='job_description',
            field=models.TextField(blank=True),
        ),
    ]
