# Generated by Django 5.2.12 on 2026-03-25 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextstep', '0003_alter_application_job_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nextstep.application')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nextstep.tag')),
            ],
            options={
                'unique_together': {('application', 'tag')},
            },
        ),
        migrations.AddField(
            model_name='application',
            name='tags',
            field=models.ManyToManyField(related_name='tags', through='nextstep.ApplicationTag', to='nextstep.tag'),
        ),
    ]
