# Generated by Django 5.2.12 on 2026-03-25 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextstep', '0004_tag_applicationtag_application_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='colour',
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
