# Generated by Django 5.2.12 on 2026-03-25 23:19

from django.db import migrations


def create_default_tags(apps, schema_editor):
    # We fetch the model from the historical state of the app
    Tag = apps.get_model("nextstep", "Tag")

    STATUS_DATA = {
        "Applied": "3B82F6",
        "Interviewing": "F59E0B",
        "Offer": "10B981",
        "Rejected": "EF4444",
        "Ghosted": "6B7280",
    }

    for name, hex_val in STATUS_DATA.items():
        Tag.objects.get_or_create(name=name, defaults={"colour": hex_val})


class Migration(migrations.Migration):
    dependencies = [
        ("nextstep", "0005_tag_colour"),
    ]

    operations = [migrations.RunPython(code=create_default_tags)]
