# Generated by Django 5.2.12 on 2026-03-27 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextstep', '0006_auto_20260325_2319'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='applicationtag',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='tag',
            name='colour',
            field=models.CharField(default='3B82F6', max_length=8),
        ),
    ]
