# Generated by Django 5.2.12 on 2026-03-30 04:42

import django.db.models.deletion
import encrypted_model_fields.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextstep', '0008_tag_user_emailintegration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEmailAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('GMAIL', 'Google Gmail'), ('OUTLOOK', 'Microsoft Outlook'), ('IMAP', 'Generic IMAP (Yahoo, iCloud, etc.)')], max_length=10)),
                ('email_address', models.EmailField(max_length=254)),
                ('access_token', encrypted_model_fields.fields.EncryptedTextField(blank=True, null=True)),
                ('refresh_token', encrypted_model_fields.fields.EncryptedTextField(blank=True, null=True)),
                ('token_expiry', models.DateTimeField(blank=True, null=True)),
                ('imap_server', models.CharField(blank=True, max_length=255, null=True)),
                ('imap_password', encrypted_model_fields.fields.EncryptedTextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
