# Use the official Python slim image
FROM python:3.12-slim-bookworm

# 1. Install system dependencies & Bun
RUN apt-get update && apt-get install -y --no-install-recommends \
    curl \
    ca-certificates \
    unzip \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# 2. Install uv
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

# 3. Set working directory
WORKDIR /code

# 4. Install Python dependencies using uv
ENV UV_PROJECT_ENVIRONMENT=/opt/venv
ENV PATH="/opt/venv/bin:$PATH"

COPY pyproject.toml .
COPY uv.lock .
RUN uv sync --frozen --no-cache

# 6. Copy the rest of the code
COPY . .

WORKDIR /code/src

CMD ["celery", "-A", "settings", "worker", "--loglevel=info"]
